### ISSUE TITLE
The Knapsack Problem (JAVA implementation)

### ISSUE THREAD

**Issue by srsandy** [srsandy/DSA-in-JAVA#14]
**Add java file Chapter-6 folder**

**Write a program that solves the knapsack problem for an arbitrary knapsack capacity and series of weights. Assume the weights are stored in an array. Hint: The arguments to the recursive knapsack() function are the target weight and the array index where the remaining items start.**

Your Code must follow the algorithm given on **page no. 305** of the pdf book which is inside the book.

**Comment by gane5hvarma** [comment]
solved

**Comment by tushar-nitave** [comment]
Is this still open?

**Comment by srsandy** [comment]
@tushar-nitave You can still add your approach.

**Comment by tushar-nitave** [comment]
ok

**Comment by Rimjhim28** [comment]
@srsandy Can I send a PR for this?
