### ISSUE TITLE
Combinations: Picking a Team (Java Implementation)

### ISSUE THREAD

**Issue by srsandy** [srsandy/DSA-in-JAVA#15]
**Add java file Chapter-6 folder**

**Implement a recursive approach to showing all the teams that can be created from a group (n things taken k at a time). Write the recursive showTeams() method and a main() method to prompt the user for the group size and the team size to provide arguments for showTeam(), which then displays all the possible combinations.**

Refer pdf book inside the repo Pg no. 306,307, 315(6.5)

**Comment by dominikas14** [comment]
I would like to work on it

**Comment by jainsaurav52** [comment]
Solved buddy.

**Comment by srsandy** [comment]
@dominikas14 go for it.

**Comment by DominikaWojcik** [comment]
My approach is actually the same as jainsaurav52 so I will leave it as it is ;)

**Comment by jainsaurav52** [comment]
@srsandy added both the methods.
